2020-11-08 14:16:03,220 INFO    MainThread:15900 [wandb_setup.py:_flush():68] setting env: {'api_key': '4a50a6213c69c6a669deb96f81ced074ecac908a'}
2020-11-08 14:16:03,220 INFO    MainThread:15900 [wandb_setup.py:_flush():68] multiprocessing start_methods=spawn
2020-11-08 14:16:03,220 INFO    MainThread:15900 [wandb_setup.py:_flush():68] setting login settings: {}
2020-11-08 14:16:03,221 INFO    MainThread:15900 [wandb_setup.py:_flush():68] configuring jupyter hooks <wandb.sdk.wandb_init._WandbInit object at 0x000001C9318D6040>
2020-11-08 14:16:03,221 INFO    MainThread:15900 [wandb_init.py:_log_setup():301] Logging user logs to wandb\run-20201108_141603-2vl3irn6\logs\debug.log
2020-11-08 14:16:03,221 INFO    MainThread:15900 [wandb_init.py:_log_setup():302] Logging internal logs to wandb\run-20201108_141603-2vl3irn6\logs\debug-internal.log
2020-11-08 14:16:04,750 INFO    MainThread:15900 [wandb_run.py:_console_start():1322] atexit reg
2020-11-08 14:16:04,750 INFO    MainThread:15900 [wandb_run.py:_redirect():1192] redirect: SettingsConsole.WRAP
2020-11-08 14:16:04,751 INFO    MainThread:15900 [wandb_run.py:_redirect():1223] Wrapping output streams.
2020-11-08 14:16:04,751 INFO    MainThread:15900 [wandb_run.py:_redirect():1239] Redirects installed.
2020-11-08 14:16:04,835 INFO    MainThread:15900 [wandb_init.py:_pause_backend():222] pausing backend
2020-11-08 14:24:15,840 INFO    MainThread:15900 [wandb_run.py:_atexit_cleanup():1295] got exitcode: 0
2020-11-08 14:24:15,842 INFO    MainThread:15900 [wandb_run.py:_restore():1267] restore
2020-11-08 14:24:15,844 INFO    MainThread:15900 [wandb_run.py:_restore():1267] restore
2020-11-08 14:24:20,945 ERROR   MainThread:15900 [wandb_run.py:_atexit_cleanup():1313] Problem finishing run
Traceback (most recent call last):
  File "C:\Users\presu\miniconda3\envs\cs701\lib\site-packages\wandb\sdk\wandb_run.py", line 1303, in _atexit_cleanup
    self._on_finish()
  File "C:\Users\presu\miniconda3\envs\cs701\lib\site-packages\wandb\sdk\wandb_run.py", line 1447, in _on_finish
    self._backend.interface.publish_exit(self._exit_code)
  File "C:\Users\presu\miniconda3\envs\cs701\lib\site-packages\wandb\sdk\interface\interface.py", line 584, in publish_exit
    self._publish(rec)
  File "C:\Users\presu\miniconda3\envs\cs701\lib\site-packages\wandb\sdk\interface\interface.py", line 432, in _publish
    raise Exception("The wandb backend process has shutdown")
Exception: The wandb backend process has shutdown
2020-11-08 14:24:20,951 INFO    MainThread:15900 [internal.py:handle_exit():138] Internal process exited
