2020-11-08 14:29:38,880 INFO    MainThread:15964 [internal.py:wandb_internal():63] W&B internal server running at pid: 15964
2020-11-08 14:29:38,882 DEBUG   HandlerThread:15964 [handler.py:handle_request():55] handle_request: check_version
2020-11-08 14:29:38,882 INFO    WriterThread:15964 [datastore.py:open_for_write():76] open: wandb\run-20201108_142938-3qjwhs87\run-3qjwhs87.wandb
2020-11-08 14:29:38,883 DEBUG   SenderThread:15964 [sender.py:send():90] send: header
2020-11-08 14:29:38,883 DEBUG   SenderThread:15964 [sender.py:send():90] send: request
2020-11-08 14:29:38,883 DEBUG   SenderThread:15964 [sender.py:send_request():99] send_request: check_version
2020-11-08 14:29:38,885 DEBUG   Thread-8  :15964 [connectionpool.py:_new_conn():939] Starting new HTTPS connection (1): pypi.org:443
2020-11-08 14:29:38,952 DEBUG   Thread-8  :15964 [connectionpool.py:_make_request():433] https://pypi.org:443 "GET /pypi/wandb/json HTTP/1.1" 200 51383
2020-11-08 14:29:38,995 DEBUG   SenderThread:15964 [sender.py:send():90] send: run
2020-11-08 14:29:38,998 INFO    SenderThread:15964 [sender.py:_maybe_setup_resume():280] checking resume status for None/ch-en-try/3qjwhs87
2020-11-08 14:29:39,002 DEBUG   SenderThread:15964 [connectionpool.py:_new_conn():939] Starting new HTTPS connection (1): api.wandb.ai:443
2020-11-08 14:29:39,129 DEBUG   SenderThread:15964 [connectionpool.py:_make_request():433] https://api.wandb.ai:443 "POST /graphql HTTP/1.1" 200 None
2020-11-08 14:29:39,157 DEBUG   SenderThread:15964 [util.py:is_cygwin_git():315] Failed checking if running in CYGWIN due to: FileNotFoundError(2, 'The system cannot find the file specified', None, 2, None)
2020-11-08 14:29:39,160 DEBUG   SenderThread:15964 [cmd.py:execute():718] Popen(['git', 'cat-file', '--batch-check'], cwd=D:\Academics\Fall 2020\CS 701 Seminar\Bo-Eng-Machine-Transation, universal_newlines=False, shell=None, istream=<valid stream>)
2020-11-08 14:29:39,218 DEBUG   SenderThread:15964 [connectionpool.py:_new_conn():939] Starting new HTTPS connection (1): api.wandb.ai:443
2020-11-08 14:29:39,348 DEBUG   SenderThread:15964 [connectionpool.py:_make_request():433] https://api.wandb.ai:443 "POST /graphql HTTP/1.1" 200 None
2020-11-08 14:29:39,381 DEBUG   HandlerThread:15964 [handler.py:handle_request():55] handle_request: run_start
2020-11-08 14:29:39,384 INFO    SenderThread:15964 [dir_watcher.py:__init__():164] watching files in: wandb\run-20201108_142938-3qjwhs87\files
2020-11-08 14:29:39,384 INFO    SenderThread:15964 [sender.py:_start_run_threads():487] run started: 3qjwhs87 with start time 1604863778
2020-11-08 14:29:39,384 DEBUG   SenderThread:15964 [sender.py:send():90] send: summary
2020-11-08 14:29:39,385 INFO    SenderThread:15964 [sender.py:_save_file():568] saving file wandb-summary.json with policy end
2020-11-08 14:29:39,408 DEBUG   HandlerThread:15964 [cmd.py:execute():718] Popen(['git', 'cat-file', '--batch-check'], cwd=D:\Academics\Fall 2020\CS 701 Seminar\Bo-Eng-Machine-Transation, universal_newlines=False, shell=None, istream=<valid stream>)
2020-11-08 14:29:39,460 DEBUG   HandlerThread:15964 [cmd.py:execute():718] Popen(['git', 'rev-parse', '--show-toplevel'], cwd=D:\Academics\Fall 2020\CS 701 Seminar\Bo-Eng-Machine-Transation, universal_newlines=False, shell=None, istream=None)
2020-11-08 14:29:39,611 DEBUG   SenderThread:15964 [sender.py:send():90] send: files
2020-11-08 14:29:39,611 INFO    SenderThread:15964 [sender.py:_save_file():568] saving file wandb-metadata.json with policy now
2020-11-08 14:29:39,611 DEBUG   HandlerThread:15964 [handler.py:handle_request():55] handle_request: status
2020-11-08 14:29:39,612 DEBUG   SenderThread:15964 [sender.py:send():90] send: request
2020-11-08 14:29:39,613 DEBUG   SenderThread:15964 [sender.py:send_request():99] send_request: status
2020-11-08 14:29:39,615 DEBUG   SenderThread:15964 [connectionpool.py:_new_conn():939] Starting new HTTPS connection (1): api.wandb.ai:443
2020-11-08 14:29:39,623 DEBUG   Thread-17 :15964 [connectionpool.py:_new_conn():939] Starting new HTTPS connection (1): api.wandb.ai:443
2020-11-08 14:29:39,773 DEBUG   SenderThread:15964 [connectionpool.py:_make_request():433] https://api.wandb.ai:443 "POST /graphql HTTP/1.1" 200 None
2020-11-08 14:29:39,776 DEBUG   SenderThread:15964 [sender.py:send():90] send: config
2020-11-08 14:29:39,782 DEBUG   SenderThread:15964 [connectionpool.py:_new_conn():939] Starting new HTTPS connection (1): api.wandb.ai:443
2020-11-08 14:29:39,792 DEBUG   Thread-17 :15964 [connectionpool.py:_make_request():433] https://api.wandb.ai:443 "POST /graphql HTTP/1.1" 200 None
2020-11-08 14:29:39,795 DEBUG   Thread-17 :15964 [connectionpool.py:_new_conn():939] Starting new HTTPS connection (1): storage.googleapis.com:443
2020-11-08 14:29:39,934 DEBUG   SenderThread:15964 [connectionpool.py:_make_request():433] https://api.wandb.ai:443 "POST /graphql HTTP/1.1" 200 None
2020-11-08 14:29:40,089 DEBUG   Thread-17 :15964 [connectionpool.py:_make_request():433] https://storage.googleapis.com:443 "PUT /wandb-production.appspot.com/submalpast/ch-en-try/3qjwhs87/wandb-metadata.json?Expires=1604950179&GoogleAccessId=wandb-production%40appspot.gserviceaccount.com&Signature=UlSISlowyNJJPHOdtm9gINTj5LgGH3DnLs8FlegCyBnCpq3Dsj0hyxbeevP5aRO6eZwvhlSGuMw9oNRRySI3HpZI06ib1jdhOiMQiLhmJ8Ch7w3K78E4LLNP834UshRaFR9CL%2Bb3ijBVnY36yo%2FMvE43EbcDlGuSva1ityTBt%2B0xTE6hr0qL9x9GKQjnvq372VXt%2FMbhp6F84oLILnYHqP0x9JzfLQluMrohVfvOCw8IRvpZsMow8WqlC3Rmhojkw46Zr%2BcnRxErOy%2BO%2Bf7BNbw9C7SD27XWy86IW33yYxPUPLV3YmgmGAnX08NTPR47Yv0fq9IdA096ZcviKqdQMA%3D%3D HTTP/1.1" 200 0
2020-11-08 14:29:40,091 INFO    Thread-17 :15964 [upload_job.py:push():131] Uploaded file C:\Users\presu\AppData\Local\Temp\tmpay1fp5qkwandb\3t0ixmur-wandb-metadata.json
2020-11-08 14:29:40,397 INFO    Thread-12 :15964 [dir_watcher.py:_on_file_modified():225] file/dir modified: wandb\run-20201108_142938-3qjwhs87\files\config.yaml
2020-11-08 14:29:40,397 INFO    Thread-12 :15964 [dir_watcher.py:_on_file_created():212] file/dir created: wandb\run-20201108_142938-3qjwhs87\files\wandb-summary.json
2020-11-08 14:29:40,397 INFO    Thread-12 :15964 [dir_watcher.py:_on_file_created():212] file/dir created: wandb\run-20201108_142938-3qjwhs87\files\requirements.txt
2020-11-08 14:29:40,398 INFO    Thread-12 :15964 [dir_watcher.py:_on_file_created():212] file/dir created: wandb\run-20201108_142938-3qjwhs87\files\wandb-metadata.json
2020-11-08 14:29:40,398 INFO    Thread-12 :15964 [dir_watcher.py:_on_file_created():212] file/dir created: wandb\run-20201108_142938-3qjwhs87\files\output.log
2020-11-08 14:29:40,646 INFO    WriterThread:15964 [datastore.py:close():257] close: wandb\run-20201108_142938-3qjwhs87\run-3qjwhs87.wandb
2020-11-08 14:29:40,647 INFO    HandlerThread:15964 [handler.py:finish():271] shutting down handler
2020-11-08 14:29:40,894 ERROR   MainThread:15964 [internal.py:wandb_internal():129] Thread SenderThread:
Traceback (most recent call last):
  File "C:\Users\presu\miniconda3\envs\cs701\lib\site-packages\wandb\sdk\internal\internal_util.py", line 33, in run
    self._run()
  File "C:\Users\presu\miniconda3\envs\cs701\lib\site-packages\wandb\sdk\internal\internal_util.py", line 60, in _run
    self._process(record)
  File "C:\Users\presu\miniconda3\envs\cs701\lib\site-packages\wandb\sdk\internal\internal.py", line 233, in _process
    self._sm.send(record)
  File "C:\Users\presu\miniconda3\envs\cs701\lib\site-packages\wandb\sdk\internal\sender.py", line 92, in send
    send_handler(record)
  File "C:\Users\presu\miniconda3\envs\cs701\lib\site-packages\wandb\sdk\internal\sender.py", line 564, in send_config
    config_util.save_config_file_from_dict(config_path, config_dict)
  File "C:\Users\presu\miniconda3\envs\cs701\lib\site-packages\wandb\sdk\lib\config_util.py", line 48, in save_config_file_from_dict
    conf_file.write(data)
  File "C:\Users\presu\miniconda3\envs\cs701\lib\encodings\cp1252.py", line 19, in encode
    return codecs.charmap_encode(input,self.errors,encoding_table)[0]
UnicodeEncodeError: 'charmap' codec can't encode character '\u2581' in position 388: character maps to <undefined>
2020-11-08 14:29:40,912 DEBUG   raven-sentry.BackgroundWorker:15964 [connectionpool.py:_new_conn():939] Starting new HTTPS connection (1): o151352.ingest.sentry.io:443
2020-11-08 14:29:41,120 DEBUG   raven-sentry.BackgroundWorker:15964 [connectionpool.py:_make_request():433] https://o151352.ingest.sentry.io:443 "POST /api/5288891/store/ HTTP/1.1" 200 41
2020-11-08 14:29:41,804 DEBUG   Thread-9  :15964 [connectionpool.py:_new_conn():939] Starting new HTTPS connection (1): api.wandb.ai:443
2020-11-08 14:29:41,963 DEBUG   Thread-9  :15964 [connectionpool.py:_make_request():433] https://api.wandb.ai:443 "POST /files/submalpast/ch-en-try/3qjwhs87/file_stream HTTP/1.1" 200 None
2020-11-08 14:29:42,914 INFO    MainThread:15964 [internal.py:handle_exit():138] Internal process exited
